excluded:
  - "**/.build/"

disabled_rules:
  - trailing_comma
  - opening_brace
opt_in_rules:
  - force_unwrapping
  - implicit_return
  
force_unwrapping: error

line_length:
  warning: 160
  error: 180
